[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Permet d'appeler les fonctions via /api/nom-de-la-fonction
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
